# Generated by Django 3.2.18 on 2023-03-05 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230303_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', validators=[django.core.validators.MinValueValidator(1, 'Amount must be one or more')], verbose_name='Ingredient is recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Time must be one or more')], verbose_name='cooking time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='foodgram/media/', verbose_name='Image'),
        ),
    ]
